const $=x=>document.getElementById(x),money=x=>new Intl.NumberFormat("he-IL",{style:"currency",currency:"ILS",maximumFractionDigits:0}).format(x),mean=a=>a.reduce((s,x)=>s+x,0)/a.length,clamp=x=>Math.max(0,Math.min(100,Math.round(x)));
let market=null,fx=null,a=null,plan=localStorage.getItem("v4plan")||"balanced";const exp={conservative:.25,balanced:.5,growth:.8},names={conservative:"שמרני",balanced:"מאוזן",growth:"צמיחה"};
function analyze(p){let c=p.map(x=>x.close),last=c[0],r5=(last/c[Math.min(5,c.length-1)]-1)*100,r20=(last/c[Math.min(20,c.length-1)]-1)*100,r60=(last/c[Math.min(60,c.length-1)]-1)*100,s20=mean(c.slice(0,20)),s60=mean(c.slice(0,60)),rs=[];for(let i=0;i<c.length-1;i++)rs.push(c[i]/c[i+1]-1);let m=mean(rs),vol=Math.sqrt(mean(rs.map(x=>(x-m)**2)))*Math.sqrt(252)*100,marketS=clamp(50+r60*2),trend=clamp(50+(last/s20-1)*500+(s20/s60-1)*400),risk=clamp(90-vol*2.2),mom=clamp(50+r5*3+r20*1.5),master=clamp((marketS+trend+risk+mom)/4);return{last,r5,r20,r60,vol,marketS,trend,risk,mom,master,signal:master>=70?"חיובי":master>=55?"חיובי מתון":master>=45?"ניטרלי":master>=30?"זהירות":"שלילי"}}
function renderAgents(){if(!a)return;let x=[["Market",a.marketS,`60 ימים ${a.r60.toFixed(1)}%`],["Trend",a.trend,`20 ימים ${a.r20.toFixed(1)}%`],["Risk",a.risk,`תנודתיות ${a.vol.toFixed(1)}%`],["Momentum",a.mom,`5 ימים ${a.r5.toFixed(1)}%`],["Portfolio",a.master,a.signal]];$("agents").innerHTML=x.map(([n,s,t])=>`<div class="card"><b>${n} Agent</b><div class="score">${s}/100</div><div class="bar"><i style="width:${s}%"></i></div><div class="muted">${t}</div></div>`).join("")}
async function load(){try{$("status").textContent="טוען שוק ומט״ח...";$("error").style.display="none";let [mr,fr]=await Promise.all([fetch(`${APP_CONFIG.marketEndpoint}?symbol=${$("symbol").value}`),fetch(APP_CONFIG.fxEndpoint)]),mj=await mr.json(),fj=await fr.json();if(!mr.ok)throw Error(mj.error||"Market API error");if(!fr.ok)throw Error(fj.error||"FX API error");market=mj;fx=fj;a=analyze(mj.prices);$("price").innerHTML=`<span class=ltr>$${a.last.toFixed(2)}</span>`;$("marketDate").textContent=mj.lastRefreshed;$("fx").textContent=fj.rate.toFixed(4);$("fxDate").textContent=fj.lastRefreshed;$("master").textContent=a.master+"/100";$("signal").textContent=a.signal;$("status").textContent="נתוני שוק ומט״ח נטענו";renderAgents();renderPaper()}catch(e){$("error").textContent=e.message;$("error").style.display="block";$("status").textContent="שגיאת טעינה"}}
function paper(){return JSON.parse(localStorage.getItem("v4paper")||"null")}function save(p){localStorage.setItem("v4paper",JSON.stringify(p));renderPaper()}
function openPaper(){if(!market||!fx)return alert("טען שוק ומט״ח תחילה");let cap=Math.max(1000,+$("capital").value||100000),ils=cap*exp[plan],usd=ils/fx.rate,units=usd/a.last;save({symbol:market.symbol,start:cap,allocatedILS:ils,allocatedUSD:usd,entryFX:fx.rate,entryPrice:a.last,units,cashILS:cap-ils,date:market.lastRefreshed,plan})}
function currentValue(p){let px=(market&&market.symbol===p.symbol&&a)?a.last:p.entryPrice,rate=fx?fx.rate:p.entryFX,marketILS=p.units*px*rate,total=p.cashILS+marketILS;return{px,rate,marketILS,total,pnl:total-p.start}}
function renderPaper(){let p=paper(),cap=Math.max(1000,+$("capital").value||100000);$("start").textContent=money(p?p.start:cap);if(!p){$("value").textContent=money(cap);$("pnl").textContent="—";$("position").innerHTML='<tr><td colspan="8" class="muted">אין פוזיציה.</td></tr>';return}let v=currentValue(p),pc=v.pnl/p.start*100;$("value").textContent=money(v.total);$("pnl").textContent=`${v.pnl>=0?"+":""}${money(v.pnl)} (${pc.toFixed(2)}%)`;$("pnl").className=v.pnl>=0?"green":"red";$("position").innerHTML=`<tr><td>${p.symbol}</td><td>${money(p.allocatedILS)}</td><td><span class=ltr>$${p.allocatedUSD.toFixed(2)}</span></td><td>${p.entryFX.toFixed(4)}</td><td><span class=ltr>$${p.entryPrice.toFixed(2)}</span></td><td><span class=ltr>${p.units.toFixed(4)}</span></td><td>${money(v.marketILS)}</td><td class="${v.pnl>=0?"green":"red"}">${v.pnl>=0?"+":""}${money(v.pnl)}</td></tr>`}
function snapshots(){return JSON.parse(localStorage.getItem("v4snaps")||"[]")}function snapshot(){let p=paper();if(!p||!market||!fx||!a)return alert("יש לפתוח פוזיציה ולטעון נתונים");let v=currentValue(p),s=snapshots(),stamp=market.lastRefreshed,key=p.symbol+"-"+stamp;if(!s.some(x=>x.key===key)){s.push({key,date:stamp,symbol:p.symbol,value:v.total,pnl:v.pnl,fx:fx.rate,score:a.master});s.sort((x,y)=>x.date.localeCompare(y.date));localStorage.setItem("v4snaps",JSON.stringify(s.slice(-365)))}renderHistory()}
function renderHistory(){let s=snapshots();$("snapCount").textContent=s.length+" Snapshots";$("journal").innerHTML=s.length?[...s].reverse().map(x=>`<tr><td>${x.date}</td><td>${x.symbol}</td><td>${money(x.value)}</td><td class="${x.pnl>=0?"green":"red"}">${x.pnl>=0?"+":""}${money(x.pnl)}</td><td>${x.fx.toFixed(4)}</td><td>${x.score}/100</td></tr>`).join(""):'<tr><td colspan="6" class="muted">אין Snapshots.</td></tr>';if(s.length>1){let r=(s.at(-1).value/s[0].value-1)*100;$("performanceText").textContent=`שינוי בין Snapshot ראשון לאחרון: ${r>=0?"+":""}${r.toFixed(2)}%`}draw(s)}
function draw(s){let c=$("chart"),r=c.getBoundingClientRect(),d=devicePixelRatio||1;c.width=r.width*d;c.height=r.height*d;let x=c.getContext("2d");x.scale(d,d);x.clearRect(0,0,r.width,r.height);if(s.length<2){x.fillStyle="#9eb5ca";x.font="14px Arial";x.fillText("נדרשים לפחות שני Snapshots להצגת גרף",20,40);return}let vals=s.map(q=>q.value),mn=Math.min(...vals),mx=Math.max(...vals),sp=Math.max(1,mx-mn);x.strokeStyle="#39b4ff";x.lineWidth=2.5;x.beginPath();vals.forEach((v,i)=>{let px=15+(r.width-30)*i/(vals.length-1),py=15+(r.height-30)*(1-(v-mn)/sp);i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke()}
function closeP(){if(paper()&&!confirm("לסגור את פוזיציית הנייר?"))return;localStorage.removeItem("v4paper");renderPaper()}$("load").onclick=load;$("open").onclick=openPaper;$("snapshot").onclick=snapshot;$("close").onclick=closeP;$("reset").onclick=()=>{if(confirm("לאפס את תיק הנייר ואת ה-Snapshots?")){localStorage.removeItem("v4paper");localStorage.removeItem("v4snaps");renderPaper();renderHistory()}};$("plan").textContent=names[plan];$("expo").textContent=exp[plan]*100+"% חשיפה";renderPaper();renderHistory();window.addEventListener("resize",()=>draw(snapshots()));