const $=x=>document.getElementById(x),money=x=>new Intl.NumberFormat("he-IL",{style:"currency",currency:"ILS",maximumFractionDigits:0}).format(x),mean=a=>a.reduce((s,x)=>s+x,0)/a.length,clamp=x=>Math.max(0,Math.min(100,Math.round(x)));
let data=null,analysis=null,plan=localStorage.getItem("labV3Plan")||"balanced";
const exposure={conservative:.25,balanced:.5,growth:.8},names={conservative:"שמרני",balanced:"מאוזן",growth:"צמיחה"};
function choose(p){plan=p;localStorage.setItem("labV3Plan",p);["pc","pb","pg"].forEach(x=>$(x).classList.remove("selected"));$({conservative:"pc",balanced:"pb",growth:"pg"}[p]).classList.add("selected");$("activePlan").textContent=names[p];$("exposure").textContent=`${exposure[p]*100}% חשיפת שוק`;renderPaper()}window.choose=choose;
function calc(pr){let c=pr.map(x=>x.close),last=c[0],r5=(last/c[Math.min(5,c.length-1)]-1)*100,r20=(last/c[Math.min(20,c.length-1)]-1)*100,r60=(last/c[Math.min(60,c.length-1)]-1)*100,s20=mean(c.slice(0,Math.min(20,c.length))),s60=mean(c.slice(0,Math.min(60,c.length))),rets=[];for(let i=0;i<c.length-1;i++)rets.push(c[i]/c[i+1]-1);let m=mean(rets),vol=Math.sqrt(mean(rets.map(x=>(x-m)**2)))*Math.sqrt(252)*100;
let market=clamp(50+r60*2),trend=clamp(50+(last/s20-1)*500+(s20/s60-1)*400),risk=clamp(90-vol*2.2),momentum=clamp(50+r5*3+r20*1.5),portfolio=clamp(market*.25+trend*.25+risk*.25+momentum*.25),signal=portfolio>=70?"חיובי":portfolio>=55?"חיובי מתון":portfolio>=45?"ניטרלי":portfolio>=30?"זהירות":"שלילי";return{last,r5,r20,r60,vol,market,trend,risk,momentum,portfolio,signal}}
function score(id,val,text){$(id).textContent=val+"/100";$("b"+id.slice(1)).style.width=val+"%";$("t"+id.slice(1)).textContent=text}
async function load(){try{$("status").textContent="טוען נתונים...";$("error").style.display="none";let s=$("symbol").value,r=await fetch(`${APP_CONFIG.marketEndpoint}?symbol=${s}`),j=await r.json();if(!r.ok)throw Error(j.error||"שגיאת API");data=j;analysis=calc(j.prices);$("price").innerHTML=`<span class="ltr">$${analysis.last.toFixed(2)}</span>`;$("date").textContent="עודכן: "+j.lastRefreshed;$("masterScore").textContent=analysis.portfolio+"/100";$("signal").textContent=analysis.signal;
score("sMarket",analysis.market,`60 ימים: ${analysis.r60.toFixed(1)}%`);score("sTrend",analysis.trend,`20 ימים: ${analysis.r20.toFixed(1)}%`);score("sRisk",analysis.risk,`תנודתיות: ${analysis.vol.toFixed(1)}%`);score("sMomentum",analysis.momentum,`5 ימים: ${analysis.r5.toFixed(1)}%`);score("sPortfolio",analysis.portfolio,analysis.signal);$("status").textContent="נתוני שוק נטענו";addDecision();renderPaper()}catch(e){$("error").textContent=e.message;$("error").style.display="block";$("status").textContent="שגיאת חיבור"}}
function paper(){return JSON.parse(localStorage.getItem("labV3Paper")||"null")}function savePaper(x){localStorage.setItem("labV3Paper",JSON.stringify(x));renderPaper()}
function openPaper(){if(!data||!analysis)return alert("יש לטעון נתוני שוק תחילה");let cap=Math.max(1000,+$("capital").value||100000),alloc=cap*exposure[plan],units=alloc/analysis.last;savePaper({symbol:data.symbol,entry:analysis.last,units,cash:cap-alloc,start:cap,date:data.lastRefreshed,plan})}
function closePaper(){let p=paper();if(!p)return;if(!analysis||data.symbol!==p.symbol)return alert("טען תחילה את נתוני הנכס שבתיק");let final=p.cash+p.units*analysis.last,closed=JSON.parse(localStorage.getItem("labV3Closed")||"[]");closed.unshift({...p,exit:analysis.last,final,closeDate:data.lastRefreshed});localStorage.setItem("labV3Closed",JSON.stringify(closed.slice(0,50)));localStorage.removeItem("labV3Paper");renderPaper()}
function renderPaper(){let p=paper(),cap=Math.max(1000,+$("capital").value||100000);$("startCapital").textContent=money(p?p.start:cap);if(!p){$("paperValue").textContent=money(cap);$("paperPnl").textContent="טרם נפתחה פוזיציה";$("positions").innerHTML='<tr><td colspan="6" class="muted">עדיין לא נפתחה פוזיציה.</td></tr>';return}let current=(analysis&&data.symbol===p.symbol)?analysis.last:p.entry,val=p.cash+p.units*current,pnl=val-p.start,pct=pnl/p.start*100;$("paperValue").textContent=money(val);$("paperPnl").textContent=`${pnl>=0?"+":""}${money(pnl)} (${pct.toFixed(2)}%)`;$("paperPnl").className=pnl>=0?"green":"red";$("positions").innerHTML=`<tr><td>${p.symbol}</td><td><span class="ltr">$${p.entry.toFixed(2)}</span></td><td><span class="ltr">${p.units.toFixed(4)}</span></td><td><span class="ltr">$${current.toFixed(2)}</span></td><td>${money(p.units*current)}</td><td class="${pnl>=0?"green":"red"}">${pnl>=0?"+":""}${money(pnl)}</td></tr>`}
function addDecision(){let a=JSON.parse(localStorage.getItem("labV3Journal")||"[]"),key=data.symbol+"-"+data.lastRefreshed;if(!a.some(x=>x.key===key)){a.unshift({key,date:data.lastRefreshed,symbol:data.symbol,score:analysis.portfolio,plan:names[plan],price:analysis.last.toFixed(2),decision:analysis.signal});localStorage.setItem("labV3Journal",JSON.stringify(a.slice(0,60)))}renderJournal()}
function renderJournal(){let a=JSON.parse(localStorage.getItem("labV3Journal")||"[]");$("journal").innerHTML=a.length?a.map(x=>`<tr><td>${x.date}</td><td>${x.symbol}</td><td>${x.score}/100</td><td>${x.plan}</td><td><span class="ltr">$${x.price}</span></td><td>${x.decision}</td></tr>`).join(""):'<tr><td colspan="6" class="muted">אין עדיין החלטות שמורות.</td></tr>'}
$("load").onclick=load;$("openPaper").onclick=openPaper;$("closePaper").onclick=closePaper;$("resetPaper").onclick=()=>{localStorage.removeItem("labV3Paper");renderPaper()};$("capital").onchange=renderPaper;choose(plan);renderJournal();renderPaper();