import {createPaper,normalizeBars,runPaperCycle,paperValue,backtestDaily,RULES,restorePaperState} from './lib/meitav-paper.mjs';
import {evaluateWaveStrategy} from './lib/meitav-wave-strategy.mjs';
const $=s=>document.querySelector(s),key='levi.meitav.paper.v1',fmt=n=>Number(n).toLocaleString('he-IL',{maximumFractionDigits:2}),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state={paper:createPaper(),markets:[]},selected=null;
try{const s=JSON.parse(localStorage.getItem(key));if(s)state=restorePaperState(s);}catch{$('#status').textContent='לא ניתן לקרוא תיק שמור; התחל תיק חדש';}
$('#currency').value=state.paper.currency;$('#initial').value=state.paper.initial;$('#fee').value=state.paper.feePct;
function save(){localStorage.setItem(key,JSON.stringify(state));}
function render(){
 const p=state.paper,prices=Object.fromEntries(state.markets.map(m=>[m.symbol,m.bars.at(-1).close])),value=paperValue(p,prices),held=Object.keys(p.positions).length;
 $('#summary').innerHTML=[['שווי הדמיה',fmt(value)+' '+p.currency],['מזומן',fmt(p.cash)+' '+p.currency],['רווח / הפסד',fmt(value-p.initial)+' '+p.currency],['פוזיציות',held+'/6'],['מזומן למקום פנוי',held<6?fmt(p.cash/(6-held))+' '+p.currency:'—'],['מכירות',p.journal.filter(j=>j.type==='SELL').length]].map(([k,v])=>`<article><span>${k}</span><strong>${v}</strong></article>`).join('');
 $('#markets').innerHTML=state.markets.map(m=>{const s=evaluateWaveStrategy(m.bars,RULES),held=!!p.positions[m.symbol];return `<tr data-symbol="${esc(m.symbol)}" class="${held?'active-position '+(s.direction==='DOWN'?'active-down':'active-up'):''}"><td>${esc(m.symbol)}</td><td>${fmt(s.price)}</td><td>${s.direction==='UP'?'עולה':'יורד'} ${fmt(s.currentWave)}%</td><td>${held?'פוזיציה פעילה':s.buyConfirmed?'מתאים לקנייה':'ממתין'}</td></tr>`;}).join('');
 $('#markets').querySelectorAll('tr').forEach(r=>r.onclick=()=>{selected=r.dataset.symbol;draw();});
 $('#positions').innerHTML=Object.values(p.positions).map(x=>{const price=prices[x.symbol]||x.lastPrice;return `<tr><td>${esc(x.symbol)}</td><td>${fmt(x.qty)}</td><td>${fmt(x.entryPrice)}</td><td>${fmt(price)}</td><td>${fmt(x.peakPrice)}</td><td>${fmt(x.qty*price-x.cost)} ${p.currency}</td></tr>`;}).join('')||'<tr><td colspan="6">אין פוזיציות הדמיה</td></tr>';
 $('#journal').innerHTML=p.journal.slice(0,30).map(j=>`<div class="action-card"><b>${j.type==='BUY'?'קנייה':'מכירה'} · ${esc(j.symbol)}</b><span>${esc(j.date)} · ${fmt(j.amount)} ${p.currency}</span><small>${esc(j.reason)}${j.pnl!==undefined?' · רווח / הפסד '+fmt(j.pnl):''}</small></div>`).join('')||'טרם בוצעו פעולות הדמיה';
 if(!selected)selected=state.markets[0]?.symbol;draw();
}
function draw(){const m=state.markets.find(x=>x.symbol===selected);if(!m)return;const s=evaluateWaveStrategy(m.bars,RULES),rows=m.bars.slice(-180),all=m.bars;
 $('#chartTitle').textContent=m.symbol;$('#meta').textContent=`${m.source} · סגירה אחרונה ${m.bars.at(-1).date} · ${m.currency} · קו כחול: מחיר; קו צהוב: MA200`;
 const mas=all.map((_,i)=>i>=199?all.slice(i-199,i+1).reduce((n,b)=>n+b.close,0)/200:null).slice(-rows.length),vals=[...rows.map(b=>b.close),...mas.filter(v=>v!==null)],lo=Math.min(...vals)*.98,hi=Math.max(...vals)*1.02;
 const point=(v,i)=>`${40+i/(rows.length-1)*810},${315-(v-lo)/(hi-lo)*270}`;
 $('#chart').innerHTML=`<polyline fill="none" stroke="#65c2ff" stroke-width="2" points="${rows.map((b,i)=>point(b.close,i)).join(' ')}"/><polyline fill="none" stroke="#ffd36a" stroke-width="2" points="${mas.map((v,i)=>v===null?'':point(v,i)).filter(Boolean).join(' ')}"/><text x="40" y="350" fill="#aaa">${rows[0].date}</text><text x="720" y="350" fill="#aaa">${rows.at(-1).date}</text>`;
 $('#technical').innerHTML=[['MA200',fmt(s.ma)],['גל נוכחי',fmt(s.currentWave)+'%'],['ירידה קודמת',s.previousDownWave===null?'—':fmt(s.previousDownWave)+'%'],['תנאי קנייה',s.buyConfirmed?'מתקיימים':'לא מתקיימים']].map(([k,v])=>`<div><span>${k}</span><strong>${v}</strong></div>`).join('');
 $('#backtest').textContent='';
}
function add(m){if(m.currency!==state.paper.currency)throw Error('מטבע המניה שונה ממטבע התיק. אין המרת מטבע אוטומטית.');m.bars=normalizeBars(m.bars);const old=state.markets.find(x=>x.symbol===m.symbol);if(old&&old.bars.at(-1).date>m.bars.at(-1).date)throw Error('הנתונים ישנים מהסדרה הקיימת');state.markets=state.markets.filter(x=>x.symbol!==m.symbol);state.markets.push(m);selected=m.symbol;save();render();}
async function action(fn){try{await fn();}catch(e){$('#status').textContent=e.message;}}
$('#load').onclick=()=>action(async()=>{const symbol=$('#symbol').value.trim().toUpperCase();$('#load').disabled=true;$('#status').textContent='טוען נרות יומיים…';try{const r=await fetch('/.netlify/functions/meitav-market?symbol='+encodeURIComponent(symbol),{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error||'שגיאת נתונים');add(d);$('#status').textContent='נתונים נטענו; תיק הדמיה בלבד';}finally{$('#load').disabled=false;}});
$('#csv').onchange=()=>action(async()=>{const file=$('#csv').files[0];if(!file)return;if(file.size>2000000)throw Error('קובץ גדול מדי');const raw=await file.text();if(raw.includes('"'))throw Error('ייבא CSV פשוט ללא מרכאות: Date,Close');const text=raw.replace(/^\uFEFF/,''),lines=text.trim().split(/\r?\n/),sep=lines[0].includes(';')?';':',',head=lines.shift().split(sep).map(s=>s.trim().toLowerCase());const di=head.findIndex(x=>['date','datetime'].includes(x)),ci=head.indexOf('close');if(di<0||ci<0)throw Error('כותרות CSV נדרשות: Date,Close');const symbol=$('#symbol').value.trim().toUpperCase();if(!/^[A-Z][A-Z0-9.\-]{0,11}$/.test(symbol))throw Error('סימול לא תקין');const bars=lines.filter(Boolean).map(l=>{const cells=l.split(sep);return {date:cells[di].trim(),close:Number(cells[ci])};});const today=new Date().toISOString().slice(0,10);if(bars.some(b=>b.date>=today))throw Error('ייבא רק נרות סגורים מתאריכים לפני היום');add({symbol,currency:state.paper.currency,bars,source:'CSV שהוזן ידנית'});$('#status').textContent='CSV נטען';});
$('#cycle').onclick=()=>action(()=>{runPaperCycle(state.paper,state.markets);save();render();$('#status').textContent='מחזור הדמיה הושלם על סגירות יומיות';});
$('#test').onclick=()=>action(()=>{const m=state.markets.find(m=>m.symbol===selected);if(!m)throw Error('טען מניה תחילה');const r=backtestDaily(m.bars,state.paper.feePct);$('#backtest').textContent=`בדיקה היסטורית · מודל: ${fmt(r.returnPct)}% · קנייה והחזקה: ${fmt(r.holdReturnPct)}% · ירידה מרבית: ${fmt(r.maxDrawdown)}% · פעולות: ${r.trades}. ${r.limitation}`;});
$('#reset').onclick=()=>action(()=>{if(!confirm('ליצור תיק הדמיה חדש ולמחוק את הנתונים המקומיים הקודמים?'))return;state={paper:createPaper(Number($('#initial').value),$('#currency').value,Number($('#fee').value)),markets:[]};selected=null;$('#chart').innerHTML='';$('#chartTitle').textContent='בחר מניה';$('#meta').textContent='';$('#technical').innerHTML='';$('#backtest').textContent='';save();render();});
$('#export').onclick=()=>{const u=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download='meitav-paper-backup.json';a.click();URL.revokeObjectURL(u);};
render();
