import WebSocket from "ws";import http from "node:http";import fs from "node:fs";import path from "node:path";import {fileURLToPath} from "node:url";import {URL} from "node:url";import {evaluateWaveStrategy,decidePosition} from "./lib/binance-wave-agent.mjs";
const D=path.dirname(fileURLToPath(import.meta.url)),PORT=+(process.env.PORT||8080),SYMBOLS=(process.env.BINANCE_SYMBOLS||"BTCUSDT,ETHUSDT,SOLUSDT,BNBUSDT,XRPUSDT").split(','),MIN=+(process.env.BINANCE_WAVE_MIN_PERCENT||4),MAP=+(process.env.BINANCE_MA_PERIOD||200),MAX=3,INITIAL=5000,SLOT=INITIAL/MAX,LIVE=String(process.env.BINANCE_LIVE_TRADING_ENABLED||'false')==='true';let mode='demo';
const agents=Object.fromEntries(SYMBOLS.map(symbol=>[symbol,{symbol,position:'CASH',decision:'HOLD',strategy:null,execution:'IDLE'}]));const streams=Object.fromEntries(SYMBOLS.map(s=>[s,{status:'starting',lastPrice:null}]));let paper={initialIls:INITIAL,cashIls:INITIAL,positions:{},trades:[],lastAction:null};
const value=()=>paper.cashIls+Object.entries(paper.positions).reduce((n,[s,p])=>n+p.qty*+(agents[s].strategy?.price||streams[s].lastPrice||p.entryPrice),0);const snap=()=>{const v=value();return {...paper,slotIls:SLOT,maxPositions:MAX,activePositions:Object.keys(paper.positions).length,valueIls:v,profitIls:v-INITIAL,profitPct:(v/INITIAL-1)*100}};const reset=()=>paper={initialIls:INITIAL,cashIls:INITIAL,positions:{},trades:[],lastAction:null};
function apply(s,d,price,at){price=+price;const p=paper.positions[s];if(d==='BUY'&&!p&&Object.keys(paper.positions).length<MAX&&paper.cashIls>0){const a=Math.min(SLOT,paper.cashIls);paper.positions[s]={symbol:s,qty:a/price,entryPrice:price,allocationIls:a,entryAt:at};paper.cashIls-=a;paper.lastAction={type:'BUY',symbol:s,price,at}}else if(d==='SELL'&&p){const proceeds=p.qty*price,pnlIls=proceeds-p.allocationIls,pnlPct=(price/p.entryPrice-1)*100;paper.cashIls+=proceeds;paper.trades.unshift({symbol:s,buyPrice:p.entryPrice,sellPrice:price,pnlIls,pnlPct,at});paper.trades=paper.trades.slice(0,100);delete paper.positions[s];paper.lastAction={type:'SELL',symbol:s,price,at}}}
async function j(url){const r=await fetch('https://api.binance.com'+url);if(!r.ok)throw Error('Binance '+r.status);return r.json()}async function candles(s){const r=await j(`/api/v3/klines?symbol=${s}&interval=1d&limit=${Math.max(250,MAP+30)}`),now=Date.now();return r.filter(x=>+x[6]<now).map(x=>({closeTime:+x[6],close:+x[4]}))}
async function evalOne(s){try{const c=await candles(s),st=evaluateWaveStrategy(c,{minWave:MIN,maPeriod:MAP}),pos=paper.positions[s]?'LONG':'CASH';let d=decidePosition(st,pos),ex='IDLE';if(d==='BUY'&&!paper.positions[s]&&Object.keys(paper.positions).length>=MAX){d='WAIT_NO_SLOT';ex='NO_SLOT'}if(mode==='demo'&&(d==='BUY'||d==='SELL')){apply(s,d,st.price,new Date(c.at(-1).closeTime).toISOString());ex='PAPER_EXECUTED'}agents[s]={...agents[s],position:paper.positions[s]?'LONG':'CASH',decision:d,strategy:st,lastDecisionAt:new Date().toISOString(),lastError:null,execution:ex}}catch(e){agents[s].lastError=e.message;agents[s].execution='ERROR'}}async function evalAll(){for(const s of SYMBOLS)await evalOne(s)}
for(const s of SYMBOLS){const w=new WebSocket(`wss://stream.binance.com:9443/ws/${s.toLowerCase()}@trade`);w.on('open',()=>streams[s].status='connected');w.on('message',r=>{try{const m=JSON.parse(r);streams[s].lastPrice=+m.p;streams[s].lastEventAt=new Date(m.E).toISOString()}catch{}});w.on('close',()=>streams[s].status='disconnected')}
setInterval(evalAll,300000).unref();const send=(res,o,c=200)=>{res.writeHead(c,{'Content-Type':'application/json; charset=utf-8','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Cache-Control':'no-store'});res.end(JSON.stringify(o))};
const server=http.createServer((req,res)=>{const u=new URL(req.url,`http://${req.headers.host}`);if(req.method==='OPTIONS')return send(res,{},204);const sf={'/binance-agent.html':['binance-agent.html','text/html'],'/binance-agent.js':['binance-agent.js','text/javascript'],'/binance-agent.css':['binance-agent.css','text/css']};if(req.method==='GET'&&sf[u.pathname]){const [f,t]=sf[u.pathname];res.writeHead(200,{'Content-Type':t,'Cache-Control':'no-store'});return res.end(fs.readFileSync(path.join(D,f)))}if(u.pathname==='/api/binance-mode'&&req.method==='GET')return send(res,{mode,liveTradingEnabled:LIVE,autoExecution:false,keysConfigured:false});if(u.pathname==='/api/binance-mode'&&req.method==='POST'){let b='';req.on('data',x=>b+=x);req.on('end',()=>{try{const m=JSON.parse(b).mode;if(m==='live'&&!LIVE)throw Error('LIVE is locked on server');mode=m;send(res,{ok:true,mode})}catch(e){send(res,{ok:false,error:e.message},400)}});return}if(u.pathname==='/api/binance-paper/reset'&&req.method==='POST'){reset();return send(res,{ok:true,paper:snap()})}if(u.pathname==='/api/binance-agent'&&req.method==='GET')return send(res,{mode,symbols:SYMBOLS,streams,agents:Object.values(agents),paper:snap(),config:{minWave:MIN,maPeriod:MAP,maxPositions:MAX,slotIls:SLOT,longOnly:true}});if(u.pathname==='/api/binance-agent/evaluate'&&req.method==='POST'){evalAll().then(()=>send(res,{ok:true,agents:Object.values(agents),paper:snap()}));return}if(u.pathname==='/'||u.pathname==='/health')return send(res,{ok:true,mode,symbols:SYMBOLS,paper:snap()});send(res,{error:'Not found'},404)});server.listen(PORT,'0.0.0.0',()=>{console.log('Server',PORT);evalAll()});
